# Generated by Django 3.1.7 on 2022-06-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshunt', '0003_book_podcastepisode_tutorial_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
