# Generated by Django 3.2.14 on 2022-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshunt', '0005_auto_20220708_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('book', 'Book'), ('video', 'Video'), ('tutorial', 'Tutorial'), ('podcast', 'Podcast')], max_length=20),
        ),
    ]
