# Generated by Django 3.2.14 on 2022-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshunt', '0006_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
