# Generated by Django 3.2.14 on 2024-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshunt', '0010_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
